import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Barras laterales generadas automáticamente desde la estructura de /docs:
 *  - historiaSidebar: intro (pos. 1) + las 8 partes (carpetas parte-N) + aviso legal.
 *  - castilloSidebar: las secciones del castillo.
 */
const sidebars: SidebarsConfig = {
  historiaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'historia',
    },
    'aviso-legal',
  ],

  castilloSidebar: [
    {
      type: 'autogenerated',
      dirName: 'castillo',
    },
  ],
};

export default sidebars;
